default_install_hook_types:
- pre-commit
- pre-push
- commit-msg
repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.27.0
