# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages: ["libgirepository1.0-dev", "libcairo2-dev", "pkg-config", "python3-dev", "gir1.2-gtk-4.0", "gir1.2-adw-1", "gir1.2-webkit-6.0", "make"]
  jobs:
    post_checkout:
      - git fetch --unshallow || true
      - git fetch --all --tags || true
    pre_build:
      - pytest -rP --html=pytest/report.html --cov-report html:pytest/coverage --cov=src --ignore=test/demo test
      - mkdir sphinx/source/prebuilt
      - cp -r pytest/* sphinx/source/prebuilt

sphinx:
  configuration: sphinx/source/conf.py

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
